databases:
  - name: artstoredb
    databaseName: artstoredb_ysoi
    user: azzam
services:
  - type: web
    name: ArtStore
    env: python 
    buildCommand: "./build.sh"
    startCommand: "gunicorn project.wsgi:application"
    envVars:
      - key: DATABASE_URL
          fromDatabase:
            name: artstoredb_ysoi
            property: connectionString
      - key: SECRET_KEY
        generateValue: true
      